apiVersion: v1
kind: Secret
metadata:
  name: acr-docker
  namespace: default
type: kubernetes.io/dockercfg
data:
  dockerRegistry: crarchitekt001mpsvcr.azurecr.io
  dockerId: devops-dev-test
  dockerPassword: "ushrGxAH@V4Y+15*29"